const IMAGES = [
  'ALS栖川吟狼（翠梦Program）-201101-EMERALD ILLUSION封面.jpg',
  'ALS栖川吟狼（翠梦Program）-201101.jpg',
  'ALS栖川吟狼（翠梦Program）-201102.jpg',
  'ALS栖川吟狼（翠梦Program）-2012.jpg',
  'ALS栖川吟狼（翠梦Program）-201202.jpg',
  'ALS栖川吟狼（翠梦Program）-201208-七夕.jpg',
  'ALS栖川吟狼（翠梦Program）-2013-EMERALD ILLISION Return封面.png',
  'ALS栖川吟狼（翠梦Program）-2015-圣诞节.jpg',
  'ALS栖川吟狼（翠梦Program）-2015-謹賀新年.jpg',
  'ALS栖川吟狼（翠梦Program）-2015.jpg',
  'ALS栖川吟狼（翠梦Program）-201501.jpg',
  'ALS栖川吟狼（翠梦Program）-2016-ハロウィン 01.jpg',
  'ALS栖川吟狼（翠梦Program）-2016-ハロウィン 02.jpg',
  'ALS栖川吟狼（翠梦Program）-2016-雪夜のサプライズ 01.jpg',
  'ALS栖川吟狼（翠梦Program）-2016-雪夜のサプライズ 02.jpg',
  'ALS栖川吟狼（翠梦Program）-201601-圣诞节贺图.jpg',
  'ALS栖川吟狼（翠梦Program）-2017-Rain Rain Fall 01.jpg',
  'ALS栖川吟狼（翠梦Program）-2017-Rain Rain Fall 02.jpg',
  'ALS栖川吟狼（翠梦Program）-2017-ミントの恋 01.jpg',
  'ALS栖川吟狼（翠梦Program）-2017-ミントの恋 02.jpg',
  'ALS栖川吟狼（翠梦Program）-2018-Sliver Dressing Deer.jpg',
  'ALS栖川吟狼（翠梦Program）-2018-ぐにゃぐにゃ.jpg',
  'ALS栖川吟狼（翠梦Program）-2018-カボチャの魔女.jpg',
  'ALS栖川吟狼（翠梦Program）-20180614.jpg',
  'ALS栖川吟狼（翠梦Program）-201905.jpg',
  'ALS栖川吟狼（翠梦Program）-トリック◆コメディー.jpg',
  'ALS栖川吟狼（翠梦Program）-出会い.jpg',
  'ALS栖川吟狼（翠梦Program）-夜の女王.jpg',
  'ALS栖川吟狼（翠梦Program）-寒い雪、暖かい心.jpg',
  'ALS栖川吟狼（翠梦Program）-歌琳 人设图.jpg',
  'ALS栖川吟狼（翠梦Program）-练功服小绿.jpg',
  'ALS栖川吟狼（翠梦Program）-翠梦Program封面1.jpg',
  'ALS栖川吟狼（翠梦Program）-翠梦Program相关插画06.jpg',
  'ALS栖川吟狼（翠梦Program）-翠梦Program相关插画07.jpg',
  'ALS栖川吟狼（翠梦Program）-翠梦封面.jpg',
  'ALS栖川吟狼（翠梦Program）-翡翠之梦.jpg',
  'ALS栖川吟狼（翠梦Program）-翡翠色的回忆.png',
  'ALS栖川吟狼（翠梦Program）翠梦小绿02.jpg',
  'Rvceric（翠梦Program）-2016-翠梦游戏立绘.jpg',
  '翠梦Program-歌琳·丹の陪睡DISCO 封面.webp',
];
window.IMAGES = IMAGES;
